### ISSUE TITLE
Globbing doesn't do recursion

### ISSUE THREAD

**Issue by erquhart** [75lb/renamer#15]
To get recursion, I have to add an additional `/**` per directory level. So for a directory nested four levels in, I have to target `**/**/**/**`. Is this expected behavior? I'm on Windows, but I do everything in the bash - globbing always works as expected.

**Comment by 75lb** [comment]
you don't need to write `**/**/**/**` - the expression `**` means _all_ subdirectories, no matter how deep.. 

so your expression should be `"**/*.js"` or similar - you only need the `**` once.. don't forget to enclose the expression in quotes, to prevent bash attempting filename expansion on it.

**Comment by erquhart** [comment]
Right - I would expect `**` (or `**/*.js`) to work; they do not. The presence or absence of quotes doesn't make a difference.

**Comment by 75lb** [comment]
and you're running the tool where? in cygwin for windows? which OS? 

can you paste the full command you are running?

**Comment by erquhart** [comment]
For example, given this command: `renamer --find test.js --replace spec.js 'src/**'`, a matching file that is not in the src directory will not be renamed. If that file is four levels down, the following command is needed to rename the file: `renamer --find test.js --replace spec.js 'src/**/**/**/*.js'`.

Using mingw, similar to cygwin. Again, globbing works as expected everywhere else from the bash.

**Comment by 75lb** [comment]
are there any sym-linked directories under `src`?

**Comment by erquhart** [comment]
No.






On Fri, Jun 12, 2015 at 9:32 AM -0700, "Lloyd Brookes" <notifications@github.com> wrote:












are there any sym-linked directories under src?

**Comment by tekmaven** [comment]
I can actually also confirm this.  Globbing does not work properly when I execute from Windows Command Prompt.  When I execute from Git Bash (which is mingw32 bash), it works.  This actually helped me out!

**Comment by 75lb** [comment]
ok.. which version of Windows you on @tekmaven ?

**Comment by tekmaven** [comment]
7.  I can try this tonight on 8 if you would like to see if there is a difference.

**Comment by erquhart** [comment]
No need, I'm on Windows 8.

@tekmaven are you saying globstar is working probably in mingw32 bash? That's what I'm using, and an additional globstar is required for each nested level.

**Comment by 75lb** [comment]
I'm downloading a fresh Win8.1 VM now to debug this on.. i have a feeling it's an issue in the underlying glob library (which was recently updated), we'll soon see..

**Comment by tekmaven** [comment]
@erquhart I was just trying to do ** (everything) and it worked fine for me.  It did not work at all under `cmd.exe`.

**Comment by 75lb** [comment]
could you run this test please and let me know the output? the test files are [here](https://gist.github.com/75lb/6b944fcd75836e8de2d6).

run these commands at the terminal (cmd, bash, whatever)
```sh
$ git clone https://gist.github.com/6b944fcd75836e8de2d6.git renamer-test
$ cd renamer-test
$ npm install
$ node create-files.js
$ npm test
```

do you get this output? 
```
Dry run
√ one\file1.txt -> one\file1.yeah
√ one\file2.txt -> one\file2.yeah
√ one\file3.txt -> one\file3.yeah
√ one\two\file1.txt -> one\two\file1.yeah
√ one\two\file2.txt -> one\two\file2.yeah
√ one\two\file3.txt -> one\two\file3.yeah
√ one\two\three\file1.txt -> one\two\three\file1.yeah
√ one\two\three\file2.txt -> one\two\three\file2.yeah
√ one\two\three\file3.txt -> one\two\three\file3.yeah
```

**Comment by tekmaven** [comment]
Yes, I do.

**Comment by tekmaven** [comment]
Here is the output: 
```
C:\Temp\test\renamer-test>npm test

> renamer-test@1.0.0 test C:\Temp\test\renamer-test
> renamer -f .txt -r .yeah -d one/**

Dry run
√ one\file1.txt -> one\file1.yeah
√ one\file2.txt -> one\file2.yeah
√ one\file3.txt -> one\file3.yeah
√ one\two\file1.txt -> one\two\file1.yeah
√ one\two\file2.txt -> one\two\file2.yeah
√ one\two\file3.txt -> one\two\file3.yeah
√ one\two\three\file1.txt -> one\two\three\file1.yeah
√ one\two\three\file2.txt -> one\two\three\file2.yeah
√ one\two\three\file3.txt -> one\two\three\file3.yeah
```

**Comment by 75lb** [comment]
ok, so basic recursion is working.. using this `one/two/three` folder structure can you send me a command which demonstrates it failing? Cheers!
