### ISSUE TITLE
Dry-run doesn't output anything 

### ISSUE THREAD

**Issue by Alphapage** [75lb/renamer#16]
Hello,

I'm trying to use renamer without success.
So, I tried with dry-run option, but it doesn't report anything like:
- the folder where it tries to search
- the files it found or try to find

Is there a way to verbose the output to know what it is doing ?

Thanks in advance for your help.

**Comment by 75lb** [comment]
have you tried the `--verbose` option?

**Comment by Alphapage** [comment]
I removed '' and it seems to be better.
I'm trying to rename extension like this without success:
```
renamer --find .v1.mp4 --replace .v5.mp4 lib/test --verbose
```
Could you help me a little more ?

**Comment by 75lb** [comment]
you only passed one file to that command (`lib/test`).. you need to pass all the files/folders you wish to inspect for renaming.. try this: 

`renamer --find .v1.mp4 --replace .v5.mp4 'lib/test/**/*.mp4'  --verbose --dry-run`

**Comment by 75lb** [comment]
take care, **always** start with `--dry-run`.. major damage could be done if you get your commadn wrong..

**Comment by Alphapage** [comment]
```
renamer --find .v1.mp4 --replace .v5.mp4 lib/test/**/*.mp4 --verbose --dry-run
```
It seems to hate '' on windows!

Thank you very much. It is working now. +1

**Comment by 75lb** [comment]
yeah, you don't need the quotes on Windows.. pleased it's working now.
