### ISSUE TITLE
Renaming files recursively using regex

### ISSUE THREAD

**Issue by BlackBanner** [75lb/renamer#22]
Hi,

I have a folder, that contains multiple folders with music files.
All the files in the sub folders has names started by 2 digits, "01, 02, 03,..." followed by song titles.
I wish to remove the song titles, and keeping the first 2 digits in the file names.
I believe this can be done by finding names using regex, but my trials are in vain.

example of the structure 
```javascript
 |-- Main_Folder
     |-- subfolder1
          |-- 01 songtitle.m4a
          |-- 02 songtitle.m4a
          |-- 03 songtitle.m4a
          |-- 04 songtitle.m4a
          |-- 05 songtitle.m4a
     |-- subfolder2
          |-- 01 songtitle.m4a
          |-- 02 songtitle.m4a
          |-- 03 songtitle.m4a
          |-- 04 songtitle.m4a
          |-- 05 songtitle.m4a
```

I wish it be like this
```javascript
 |-- Main_Folder
     |-- subfolder1
          |-- 01.m4a
          |-- 02.m4a
          |-- 03.m4a
          |-- 04.m4a
          |-- 05.m4a
     |-- subfolder2
          |-- 01.m4a
          |-- 02.m4a
          |-- 03.m4a
          |-- 04.m4a
          |-- 05.m4a
```
Can you help me please.

Thanks,
Ajmal

**Comment by 75lb** [comment]
i'm too busy to write the solution for you right now, but it will look something like this example: 
https://github.com/75lb/renamer#prefix-files-and-folders-recursively

Use Javascript regular expression syntax in your `--find` expression
https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by BlackBanner** [comment]
Hi,

Sorry for late reply. But thanks, it has been very helpful. 👍 

Cheers
Ajmal

**Comment by 75lb** [comment]
ok, glad it helped 👍
