### ISSUE TITLE
Any way to undo?

### ISSUE THREAD

**Issue by linck5** [75lb/renamer#23]
First I want to congratulate this package. Really simple and powerful.

But is there any way to undo your previous command? It would be very convenient.

**Comment by 75lb** [comment]
currently, there is no way to undo a rename operation.. Best practise is to always use `--dry-run` first, before making any permanent change.

**Comment by linck5** [comment]
oh, sorry I didn't notice that this command existed. That pretty much can achieve the same goal. Thank you for the reply.
