### ISSUE TITLE
using renamer programmatically

### ISSUE THREAD

**Issue by sag1v** [75lb/renamer#25]
Is there any way to use this tool programmatically in node.js?
for example:  
```
var renamer = require('renamer');
renamer('this', 'that', '*.js');
```

**Comment by 75lb** [comment]
hi @sag1v..

The programmatic API needs completely rewriting to make it easier to use. This will happen in a future version, but until then you could step through [cli.js](https://github.com/75lb/renamer/blob/master/bin/cli.js) and learn how it uses the API. I don't officially support this usage so take care, don't process your real files until 100% confident with the API.
