### ISSUE TITLE
Find and replaces multiple times

### ISSUE THREAD

**Issue by Giefdonut** [75lb/renamer#27]
1. Is it possible to run multiple find and replace, without entering multiple commands?
Im new to regex, so the commands below, might needed to optimized

**These are my commands**
renamer -e -f 'ø' -r 'oe' *
renamer -e -f 'æ' -r 'ae' *
renamer -e -f '_' -r '-' *
renamer -e -f ' ' -r '-' *

2. Is there an easy way to convert all uppercase letters to lowercase?

**Comment by 75lb** [comment]
Hi!

1. No, they are four separate operations.. 
2. On a case-sensitive system like Linux, yes. On a case-insensitive system like Windows or macOS, no.
