### ISSUE TITLE
Restart index in each folder?

### ISSUE THREAD

**Issue by mikestecker** [75lb/renamer#30]
Is there a way to restart the index in each folder?

```sh
$ renamer --replace 'Image{{index}}.jpg' **/*.jpg
```

<table>
    <thead>
        <tr><th>Before</th><th>After</th></tr>
    </thead>
    <tbody>
        <tr>
            <td><pre><code>.
├── IMG_5776.JPG
├── IMG_5778.JPG
├── pics1
    ├── IMG_5792.JPG
    └── IMG_5795.JPG
└── pics2
    ├── IMG_5786.JPG
    └── IMG_5798.JPG
</code></pre></td>
            <td><pre><code>.
├── Image1.jpg
├── Image2.jpg
├── pics1
    ├── Image1.jpg
    └── Image2.jpg
└── pics2
    ├── Image1.jpg
    └── Image2.jpg</code></pre></td>
        </tr>
    </tbody>
</table>

**Comment by 75lb** [comment]
hi, i'm afraid not - not at the moment.. you would need to fork and tweak things..

**Comment by 75lb** [comment]
You can now achieve this behaviour using the [renamer-index-dir](https://github.com/75lb/renamer-index-dir) plugin with renamer v1.0.0.
