### ISSUE TITLE
Sends usage statistics on every invocation, without any notice to the user.

### ISSUE THREAD

**Issue by conartist6** [75lb/renamer#34]
Also because there's no flag to turn it off, renamer crashes if run on a server which is not internet connected. If you'll excuse me I'm going to go look for a package that isn't spying on me, since all I want to do is rename ****ing files.

**Comment by conartist6** [comment]
I don't know for sure, but there's a decent chance that this violates the [terms of NPM](https://www.npmjs.com/policies/open-source-terms#acceptable-use), which read:

3. You will not disclose information that you do not have the right to disclose, such as confidential information of others.

4. You will not copy or share any personally identifiable information of any other person without their specific permission.

5. You will not violate any applicable law.

**Comment by 75lb** [comment]
Hi, please update renamer - you are running an old version. Usage statistics were added temporarily to identify whether it was safe to drop support for node versions older than v4.0.0. The usage stats were removed some time ago. You are 100% there should be notification to the user, my mistake - sorry.

**Comment by 75lb** [comment]
renamer v0.7.0 is the latest.. A full, more customisable rewrite is coming soon.

**Comment by conartist6** [comment]
0.7.0 is not a published version of the library on npm...

**Comment by 75lb** [comment]
Seems there is [something wrong with the npm registry](https://status.npmjs.org/).. renamer v0.7.0 is there, but you're right, it's showing an older version as the latest. Will monitor it.

**Comment by conartist6** [comment]
Huh, ok

**Comment by conartist6** [comment]
Can you verify exactly what was being sent?
It looks like:
package version
Node version
OS Type and version
Which renamer options were specified (though not the values specified for them)
the system language
the terminal resolution
the system language
"a random UUID, generated once per OS user and stored"
And of course, this being google analytics, the server IP address

Also, if the command ran longer than 5 seconds, additional reports are/were generated at 5 second intervals.

I wouldn't have minded half so much if you were just sending along the version of node, but the full list of what was being sent seems to go far beyond that.

**Comment by 75lb** [comment]
The majority of values sent are of no use, for example "system language" and "terminal resolution". The most useful stats to me were the following (below), this is what i needed to know before I could upgrade. The OS stat was pertinent as file naming works differently across OS, different path separators etc.

> package version
> Node version
> OS Type and version

GA does not collect or show IP addresses, it only converts an IP into a rough geographical region. No IP addresses are stored, only the Geo info. As you said, no options values were sent - there is no record anywhere of what people actually rename with the tool. Only their node versions etc.

The "every 5 seconds" thing sounds like a retry attempt, no additional data.

**Comment by 75lb** [comment]
npm is still down. In the meantime, this command will install the latest version directly from github (using the "git repo syntax" [described here](https://docs.npmjs.com/cli/install)).

```
npm install -g 75lb/renamer
```
