### ISSUE TITLE
Wrong doc?

### ISSUE THREAD

**Issue by cvaliere** [75lb/renamer#35]
Spent 1 hour trying to make this work:

`renamer --insensitive --find 'mpeg4' --replace 'mp4' *`

figured out this is the correct syntax:

`renamer --insensitive --find mpeg4 --replace mp4 *`

is it just me, or the doc is wrong?

**Comment by 75lb** [comment]
also, don't forget to run with `--dry-run` first

**Comment by cvaliere** [comment]
I'm on windows

the glob is not the issue, the issue is with the `--find` and `--replace` arguments

with quotes, it just does nothing
without quotes, it works

**Comment by s-h-a-d-o-w** [comment]
Finally, this was driving me nuts - thank you so much!

**Comment by 75lb** [comment]
yes, on Windows you'll need to use double-quotes - single quotes is a mac/linux thing.

I updated the README to use double-quotes instead.
