### ISSUE TITLE
Regexp finishes after first group

### ISSUE THREAD

**Issue by krisavi** [75lb/renamer#41]
Trying to do a command like: 
`renamer --find '/([^\.]+)\.[^\.]+\.(\w+)/' --replace '$1.$2' build/static/media`

file that it should apply is test.3af24c.jpg

Renamer version 1.1.0

Getting error:
`\.[\.]+\.(\w+)$/i' was unexpected at this time.`

It seems to finish after first group and not continue with regexp.

Am I missing something ?

**Comment by krisavi** [comment]
got it fixed, replaced ' with " 
`renamer --find "/([^\.]+)\.[^\.]+\.(\w+)/" --replace '$1.$2' build/static/media/*`

**Comment by 75lb** [comment]
glad you fixed.. are you on Windows?

**Comment by krisavi-powel** [comment]
Yes on windows

**Comment by 75lb** [comment]
ok thanks.. that explains the quotes thing - just checking.

>
