### ISSUE TITLE
Dry-run doesn't log anything

### ISSUE THREAD

**Issue by mhelvens** [75lb/renamer#42]
I see there is already an issue with almost this title, but that was probably for the previous version. Looking at the source-code, I don't know how dry-run _could_ log any output, because the `dryRunLog` from `rename-file.js` is written to, but never read.

**Comment by 75lb** [comment]
hi, could you send some more info to help reproduce this because it works fine for me with the latest version on macOS.. which version of renamer and which OS are you using?

**Comment by 75lb** [comment]
can you also send an example command which fails please

**Comment by mhelvens** [comment]
I'm using version 1.1.0 as an api, quite like [in this test](https://github.com/75lb/renamer/blob/master/test/api.js#L82).

Can I ask what is _supposed_ to happen when you use the `dryRun` flag? For me it simply does nothing. So far so good, nothing is renamed. But I was also expecting to see a list of everything that would be renamed if removed the flag (isn't that what would make a dry run useful?). But I don't see any place in the code where this could happen, and the unit tests don't expect it either.

**Comment by 75lb** [comment]
ah, ok - you're using the API directly.. have you had a look at [this wiki page](https://github.com/75lb/renamer/wiki/How-to-use-renamer-programmatically)? The `Renamer` class is not tightly-bound to the console or any view by default (however, the renamer _cli_ is of course). `Renamer` is observable, you subscribe to the [replace-result event](https://github.com/75lb/renamer/blob/master/docs/API.md#replace-result) and print output in the manner that suits your host application.

**Comment by mhelvens** [comment]
Makes sense. Thanks!
