### ISSUE TITLE
Can't able to add exclude directory in files options Array

### ISSUE THREAD

**Issue by kathirr007** [75lb/renamer#45]
Hi,

I was trying to use renamer to rename files programatically using this code 

/* eslint-disable */
const Renamer = require('renamer')
const renamer = new Renamer()

renamer.on('replace-result', replaceResult => {
  console.log(replaceResult)
})
let findString = new RegExp(('%d'));
let replaceString = new RegExp('$1')
renamer.rename({
  files: [ './**/*' ],
  find: /(\d+)/,
  replace: ``,
  dryRun: true
})

It does renaming the files inside node_modules also. I want to rename files but not in node_modules.

Please help me something to exclude the directories which i don't want to rename.

Thanks in advance.

**Comment by 75lb** [comment]
This command operates on everything that is _not_ underneath `node_modules`

```
$ renamer -f '/\d/g' '!(node_modules)/**' -d
```

So, the `files` pattern you need is something like `'!(node_modules)/**'`.

**Comment by 75lb** [comment]
i added an example [here](https://github.com/75lb/renamer/wiki/Examples#exclude-certain-directories)
