### ISSUE TITLE
option to only log summary

### ISSUE THREAD

**Issue by raDiesle** [75lb/renamer#49]
As we do use renamer for every build, its not needed to log every single renamed file,
instead show a one line, e.g. how many files were renamed, as it clutters the log.

What do you think?

btw. nice tool!

**Comment by 75lb** [comment]
Yes, we need this feature and it will be included in the next version..

**Comment by 75lb** [comment]
just FYI, i'm putting the finishing touches to the [next release](https://github.com/75lb/renamer/tree/mjs) which includes this feature.. 

If you would like to try it, your feedback would be appreciated..  install:

```
npm install -g renamer@next
```

To see the one-line view, add `--view one-line` to your renamer command args.. There is now also a `--silent` option.

You can define custom views and replace functions too, which I'm in the process of documenting.. Let me know if I missed anything.

**Comment by 75lb** [comment]
released in [v3](https://github.com/75lb/renamer/releases/tag/v3.0.0)
