### ISSUE TITLE
Unknown option: --regex 

### ISSUE THREAD

**Issue by ajaycallhippo** [75lb/renamer#51]
Unknown option: --regex 

![Screenshot from 2021-04-29 13-03-45](https://user-images.githubusercontent.com/67584671/116516576-64642e00-a8eb-11eb-8a3a-e4a514ef0f24.png)

can you please see this ocure issue

**Comment by 75lb** [comment]
the `--regex` option was removed in v1.0.0 back in 2018..

**Comment by 75lb** [comment]
[v1.0.0 release notes](https://github.com/75lb/renamer/releases/tag/v1.0.0)
