### ISSUE TITLE
Regex /^$/ can't work

### ISSUE THREAD

**Issue by mikcho** [75lb/renamer#56]
`renamer --find /^css$/ --replace wxss --force **/*` can't work

**Comment by 75lb** [comment]
Try using quotes.. and always use `--dry-run` to begin with:

```
renamer --find "/^css$/" --replace wxss --force "**/*"
```

**Comment by 75lb** [comment]
Also, see [this issue](https://github.com/75lb/renamer/issues/53)

**Comment by 75lb** [comment]
If you are using Git Bash, you need to escape the first forward slash, like this: 

```
renamer --find "\/^css$/" --replace wxss --force "**/*" --dry-run
```

**Comment by mikcho** [comment]
My OS is macOS, and some regex literals can't work with zsh,

Run:

```shell
renamer --find "/^css$/" --replace "scss" "**/*" --dry-run
```

Output:

```shell
Rename complete: 0 of 1 files renamed
```

Run: 

```shell
renamer --find "/\bcss\b/" --replace "scss" "**/*" --dry-run
```

Output:

```shell
✔︎ style.css → style.scss 

Rename complete: 1 of 1 files renamed.
```

But file extension of `style.css`  have not been change on filesystem.

**Comment by 75lb** [comment]
> ```shell
> renamer --find "/^css$/" --replace "scss" "**/*" --dry-run
> ```

This expression `/^css$/` will only match whole filenames which exactly equal `css`. The output you got is correct, your regular expression is wrong. 

> But file extension of `style.css` have not been change on filesystem.

Remove the `--dry-run` option to change the file on the filesystem. The `--dry-run` mode is intended for practising or testing rename expressions. Remove `--dry-run` when you are ready to perform the actual rename.
