### ISSUE TITLE
escaping hifen

### ISSUE THREAD

**Issue by FredVal** [75lb/renamer#59]
I'm trying to trim minified files that have "-min" at the the end of their name.
i'm using this command: `renamer -d --find "-min" *`
the problem is renamer is taking `-m` as an option and obviously fails with unkown option error.
I've tried to escape the hiphen with `^` but it doesnt work...

**Comment by 75lb** [comment]
try `renamer -d --find=-min *`

**Comment by FredVal** [comment]
It works!
Thanks!
