### ISSUE TITLE
 Only change the directory name doesn't work.

### ISSUE THREAD

**Issue by zystudios** [75lb/renamer#68]
I just want to change the abc directory in the dist directory to def. I use the following command

```
renamer -d  ./dist/abc --replace ./def

```

Dry run

√ ./dist/abc/ → dist\def

Rename complete: 1 of 1 files renamed.

but it doesn't work.

I don't know what went wrong. Thanks.

**Comment by 75lb** [comment]
hi, you are setting the `-d` flag (dry run) - this is a "test mode" for checking your command performs correctly.. to perform the rename operation for real, making the change on the disk, remove the `-d` flag.. 

See the top of the [examples page](https://github.com/75lb/renamer/wiki/examples): 
```
All examples include the dry-run -d flag to avoid any accidents caused by copy-pasting the commands.
```
